### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by movibe** [sglyon/jupyterlab_wakatime#1]
> /usr/local/bin/npm pack jupyterlab_wakatime
npm ERR! code E404
npm ERR! 404 Not Found: jupyterlab_wakatime@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/movibe/.npm/_logs/2018-05-13T22_28_45_868Z-debug.log

Errored, use --debug for full output:
ValueError: "jupyterlab_wakatime" is not a valid npm packag

**Comment by sglyon** [comment]
Oh sorry -- this has not been implemented yet!

I had intentions to work on this but never found the time. It isn't close to working yet. I'll make that clear in the readme.

**Comment by movibe** [comment]
I started my studies now with jupyter, I thought it cool to have started the integration with wakatime, sorry that you have no time to continue.

Anyway, congratulations to the initiative
